export const getWorkspacesCacheKey = 'getWorkspaces'
export const getWorkspaceCurrentMemberCacheKey = 'getWorkspaceCurrentMember'
export const getWorkspaceMembersCacheKey = 'getWorkspaceMembers'
export const getChannelsCacheKey = 'getChannels'
export const getWorkspaceInfoCacheKey = 'getWorkspaceInfo'
